#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define NEXUS_TOTAL_INTERRUPTS 512

#define NEXUS_HEAP_SIZE_BYTES    104857600 // 100MB heap size
#define NEXUS_HEAP_BLOCK_SIZE    4096      // 4KB block size
#define NEXUS_HEAP_ADDRESS       0x01000000
#define NEXUS_HEAP_TABLE_ADDRESS 0x00007E00

#define NEXUS_SECTOR_SIZE 512

#define NEXUS_MAX_FILESYSTEMS      16
#define NEXUS_MAX_FILE_DESCRIPTORS 512

#define NEXUS_MAX_PATH 108

#define NEXUS_TOTAL_GDT_SEGMENTS 6

#define NEXUS_PROGRAM_VIRTUAL_ADDRESS             0x400000
#define NEXUS_USER_PROGRAM_STACK_SIZE             (1024 * 16)
#define NEXUS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define NEXUS_PROGRAM_VIRTUAL_STACK_ADDRESS_END                                                    \
    (NEXUS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - NEXUS_USER_PROGRAM_STACK_SIZE)

#define NEXUS_MAX_PROGRAM_ALLOCATIONS 1024
#define NEXUS_MAX_PROCESSES           12

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1B

#define NEXUS_MAX_ISR80H_COMMANDS 1024

#define NEXUS_KEYBOARD_BUFFER_SIZE 1024
#endif
